// generated by site/build_data.py — do not edit
window.RS4_DATA = {
 "generated_at": "2026-10-05T08:45:10+01:00",
 "search_label": "Audi RS4 B7 · 2006–2008 · Manual · Petrol · UK-wide",
 "report": {
  "pdf": "report/rs4-daily-latest.pdf",
  "preview": "report/rs4-daily-latest.png",
  "updated": "2026-10-05"
 },
 "top_pick_id": "202610026598486",
 "market": {
  "total_live": 15,
  "floor_price": 10000,
  "ceiling_price": 27100,
  "lowest_mileage": 63500,
  "days_tracked": 5,
  "trend": [
   {
    "date": "2026-07-12",
    "live": 14,
    "new": 1,
    "price_changed": 0,
    "removed": 0,
    "floor": 12750,
    "median": 21995,
    "ceiling": 32989
   },
   {
    "date": "2026-08-18",
    "live": 14,
    "new": 7,
    "price_changed": 2,
    "removed": 7,
    "floor": 10000,
    "median": 21995,
    "ceiling": 27800
   },
   {
    "date": "2026-08-19",
    "live": 14,
    "new": 0,
    "price_changed": 0,
    "removed": 0,
    "floor": 10000,
    "median": 21995,
    "ceiling": 27800
   },
   {
    "date": "2026-10-04",
    "live": 15,
    "new": 0,
    "price_changed": 0,
    "removed": 0,
    "floor": 10000,
    "median": 20490,
    "ceiling": 27100
   },
   {
    "date": "2026-10-05",
    "live": 15,
    "new": 0,
    "price_changed": 0,
    "removed": 0,
    "floor": 10000,
    "median": 20490,
    "ceiling": 27100
   }
  ],
  "listings": [
   {
    "advert_id": "202610026598486",
    "title": "Audi RS4",
    "subtitle": "4.2 quattro 4dr",
    "attention_grabber": "FASH, Wingback, Mugello Blue",
    "price": 21499,
    "price_text": "£21,499",
    "year": 2006,
    "mileage": 86000,
    "mileage_text": "86,000 miles",
    "location": "Solihull (7 miles)",
    "seller_type": "Private",
    "url": "https://www.autotrader.co.uk/car-details/202610026598486",
    "image": "media/202610026598486.jpg",
    "images_hires": [
     "media/hires/202610026598486_0.jpg",
     "media/hires/202610026598486_1.jpg",
     "media/hires/202610026598486_2.jpg",
     "media/hires/202610026598486_3.jpg"
    ],
    "paint": {
     "name": "Mugello Blue",
     "hex": "#1a3f8f"
    },
    "keyword_hits": [
     "flat-bottom",
     "recaro",
     "wingback"
    ],
    "keyword_flags": [],
    "score": 3,
    "first_seen": "2026-10-04",
    "days_listed": 1,
    "price_history": [
     {
      "date": "2026-10-04",
      "price": 21499
     }
    ],
    "rank": 1
   },
   {
    "advert_id": "202607184294132",
    "title": "Audi RS4",
    "subtitle": "4.2 quattro 4dr",
    "attention_grabber": "Buckets, Flat, Carbon,Capristo",
    "price": 23000,
    "price_text": "£23,000",
    "year": 2007,
    "mileage": 88000,
    "mileage_text": "88,000 miles",
    "location": "Guisborough (147 miles)",
    "seller_type": "Trade",
    "url": "https://www.autotrader.co.uk/car-details/202607184294132",
    "image": "media/202607184294132.jpg",
    "images_hires": [
     "media/hires/202607184294132_0.jpg",
     "media/hires/202607184294132_1.jpg",
     "media/hires/202607184294132_2.jpg",
     "media/hires/202607184294132_3.jpg"
    ],
    "paint": {
     "name": "Black",
     "hex": "#0d0d0f"
    },
    "keyword_hits": [
     "bucket seats",
     "flat bottomed",
     "recaro"
    ],
    "keyword_flags": [
     "coilover"
    ],
    "score": 2,
    "first_seen": "2026-08-18",
    "days_listed": 48,
    "price_history": [
     {
      "date": "2026-08-18",
      "price": 25000
     },
     {
      "date": "2026-10-04",
      "price": 23000
     }
    ],
    "rank": 2
   },
   {
    "advert_id": "202606183421720",
    "title": "Audi RS4",
    "subtitle": "4.2 quattro 4dr",
    "attention_grabber": "WARRANTY | DELIVERY",
    "price": 20490,
    "price_text": "£20,490",
    "year": 2007,
    "mileage": 101402,
    "mileage_text": "101,402 miles",
    "location": "Congleton (50 miles)",
    "seller_type": "Trade",
    "url": "https://www.autotrader.co.uk/car-details/202606183421720",
    "image": "media/202606183421720.jpg",
    "images_hires": [
     "media/hires/202606183421720_0.jpg",
     "media/hires/202606183421720_1.jpg",
     "media/hires/202606183421720_2.jpg",
     "media/hires/202606183421720_3.jpg"
    ],
    "paint": {
     "name": "Black",
     "hex": "#0d0d0f"
    },
    "keyword_hits": [
     "recaro",
     "sports seat"
    ],
    "keyword_flags": [],
    "score": 2,
    "first_seen": "2026-07-12",
    "days_listed": 85,
    "price_history": [
     {
      "date": "2026-07-12",
      "price": 22990
     },
     {
      "date": "2026-08-18",
      "price": 22490
     },
     {
      "date": "2026-10-04",
      "price": 20490
     }
    ],
    "rank": 3
   },
   {
    "advert_id": "202607073963384",
    "title": "Audi RS4",
    "subtitle": "4.2 quattro 4dr",
    "attention_grabber": "FSH+BUCKETS+MILLTEK+BOSE",
    "price": 18995,
    "price_text": "£18,995",
    "year": 2007,
    "mileage": 106200,
    "mileage_text": "106,200 miles",
    "location": "Birmingham (5 miles)",
    "seller_type": "Trade",
    "url": "https://www.autotrader.co.uk/car-details/202607073963384",
    "image": "media/202607073963384.jpg",
    "images_hires": [
     "media/hires/202607073963384_0.jpg",
     "media/hires/202607073963384_1.jpg",
     "media/hires/202607073963384_2.jpg",
     "media/hires/202607073963384_3.jpg"
    ],
    "paint": {
     "name": "Daytona Grey",
     "hex": "#3b3f45"
    },
    "keyword_hits": [
     "bucket seats"
    ],
    "keyword_flags": [],
    "score": 1,
    "first_seen": "2026-07-12",
    "days_listed": 85,
    "price_history": [
     {
      "date": "2026-07-12",
      "price": 18995
     }
    ],
    "rank": 4
   },
   {
    "advert_id": "202609176126071",
    "title": "Audi RS4",
    "subtitle": "4.2 quattro 4dr",
    "attention_grabber": null,
    "price": 14994,
    "price_text": "£14,994",
    "year": 2006,
    "mileage": 135942,
    "mileage_text": "135,942 miles",
    "location": "Leeds (94 miles)",
    "seller_type": "Private",
    "url": "https://www.autotrader.co.uk/car-details/202609176126071",
    "image": "media/202609176126071.jpg",
    "images_hires": [
     "media/hires/202609176126071_0.jpg",
     "media/hires/202609176126071_1.jpg",
     "media/hires/202609176126071_2.jpg",
     "media/hires/202609176126071_3.jpg"
    ],
    "paint": {
     "name": "Black",
     "hex": "#0d0d0f"
    },
    "keyword_hits": [
     "bucket seats",
     "wingback"
    ],
    "keyword_flags": [
     "air ride"
    ],
    "score": 1,
    "first_seen": "2026-10-04",
    "days_listed": 1,
    "price_history": [
     {
      "date": "2026-10-04",
      "price": 14994
     }
    ],
    "rank": 5
   },
   {
    "advert_id": "202607164224569",
    "title": "Audi RS4",
    "subtitle": "4.2 quattro 4dr",
    "attention_grabber": "WINGBACKS/FLAT BOTTOM/NAV",
    "price": 12950,
    "price_text": "£12,950",
    "year": 2007,
    "mileage": 156000,
    "mileage_text": "156,000 miles",
    "location": "Birmingham (4 miles)",
    "seller_type": "Private",
    "url": "https://www.autotrader.co.uk/car-details/202607164224569",
    "image": "media/202607164224569.jpg",
    "images_hires": [
     "media/hires/202607164224569_0.jpg",
     "media/hires/202607164224569_1.jpg",
     "media/hires/202607164224569_2.jpg",
     "media/hires/202607164224569_3.jpg"
    ],
    "paint": {
     "name": "Black",
     "hex": "#0d0d0f"
    },
    "keyword_hits": [
     "flat bottom",
     "wingbacks"
    ],
    "keyword_flags": [
     "coilovers"
    ],
    "score": 1,
    "first_seen": "2026-08-18",
    "days_listed": 48,
    "price_history": [
     {
      "date": "2026-08-18",
      "price": 12350
     },
     {
      "date": "2026-10-04",
      "price": 12950
     }
    ],
    "rank": 6
   },
   {
    "advert_id": "202609306547639",
    "title": "Audi RS4",
    "subtitle": "4.2 quattro 4dr",
    "attention_grabber": "FSH - Low Mileage - 3 prev own",
    "price": 24995,
    "price_text": "£24,995",
    "year": 2007,
    "mileage": 63500,
    "mileage_text": "63,500 miles",
    "location": "Wellingborough (55 miles)",
    "seller_type": "Private",
    "url": "https://www.autotrader.co.uk/car-details/202609306547639",
    "image": "media/202609306547639.jpg",
    "images_hires": [
     "media/hires/202609306547639_0.jpg",
     "media/hires/202609306547639_1.jpg",
     "media/hires/202609306547639_2.jpg",
     "media/hires/202609306547639_3.jpg"
    ],
    "paint": {
     "name": "Daytona Grey",
     "hex": "#3b3f45"
    },
    "keyword_hits": [],
    "keyword_flags": [],
    "score": 0,
    "first_seen": "2026-10-04",
    "days_listed": 1,
    "price_history": [
     {
      "date": "2026-10-04",
      "price": 24995
     }
    ],
    "rank": 7
   },
   {
    "advert_id": "202605252687946",
    "title": "Audi RS4",
    "subtitle": "4.2 quattro 4dr",
    "attention_grabber": "stunning example!! B7 Audi RS!",
    "price": 23600,
    "price_text": "£23,600",
    "year": 2007,
    "mileage": 66000,
    "mileage_text": "66,000 miles",
    "location": "Biggleswade (75 miles)",
    "seller_type": "Private",
    "url": "https://www.autotrader.co.uk/car-details/202605252687946",
    "image": "media/202605252687946.jpg",
    "images_hires": [
     "media/hires/202605252687946_0.jpg",
     "media/hires/202605252687946_1.jpg",
     "media/hires/202605252687946_2.jpg",
     "media/hires/202605252687946_3.jpg"
    ],
    "paint": {
     "name": "Mugello Blue",
     "hex": "#1a3f8f"
    },
    "keyword_hits": [],
    "keyword_flags": [],
    "score": 0,
    "first_seen": "2026-07-12",
    "days_listed": 85,
    "price_history": [
     {
      "date": "2026-07-12",
      "price": 23800
     },
     {
      "date": "2026-08-18",
      "price": 23600
     }
    ],
    "rank": 8
   },
   {
    "advert_id": "202511047646815",
    "title": "Audi RS4",
    "subtitle": "4.2 quattro 4dr",
    "attention_grabber": "3 MONTHS WARRANTY INCLUDED!",
    "price": 21999,
    "price_text": "£21,999",
    "year": 2007,
    "mileage": 82000,
    "mileage_text": "82,000 miles",
    "location": "Rossendale (88 miles)",
    "seller_type": "Trade",
    "url": "https://www.autotrader.co.uk/car-details/202511047646815",
    "image": "media/202511047646815.jpg",
    "images_hires": [
     "media/hires/202511047646815_0.jpg",
     "media/hires/202511047646815_1.jpg",
     "media/hires/202511047646815_2.jpg",
     "media/hires/202511047646815_3.jpg"
    ],
    "paint": {
     "name": "Black",
     "hex": "#0d0d0f"
    },
    "keyword_hits": [],
    "keyword_flags": [],
    "score": 0,
    "first_seen": "2026-07-12",
    "days_listed": 85,
    "price_history": [
     {
      "date": "2026-07-12",
      "price": 21999
     }
    ],
    "rank": 9
   },
   {
    "advert_id": "202610016564051",
    "title": "Audi RS4",
    "subtitle": "4.2 quattro 4dr",
    "attention_grabber": "low mileage",
    "price": 20000,
    "price_text": "£20,000",
    "year": 2006,
    "mileage": 83000,
    "mileage_text": "83,000 miles",
    "location": "Ballindalloch (336 miles)",
    "seller_type": "Private",
    "url": "https://www.autotrader.co.uk/car-details/202610016564051",
    "image": "media/202610016564051.jpg",
    "images_hires": [
     "media/hires/202610016564051_0.jpg",
     "media/hires/202610016564051_1.jpg",
     "media/hires/202610016564051_2.jpg",
     "media/hires/202610016564051_3.jpg"
    ],
    "paint": {
     "name": "Grey",
     "hex": "#55595f"
    },
    "keyword_hits": [],
    "keyword_flags": [],
    "score": 0,
    "first_seen": "2026-10-04",
    "days_listed": 1,
    "price_history": [
     {
      "date": "2026-10-04",
      "price": 20000
     }
    ],
    "rank": 10
   },
   {
    "advert_id": "202607274556226",
    "title": "Audi RS4",
    "subtitle": "4.2 quattro 4dr",
    "attention_grabber": "Clean & Exceptional RS4",
    "price": 27100,
    "price_text": "£27,100",
    "year": 2006,
    "mileage": 88000,
    "mileage_text": "88,000 miles",
    "location": "Falkirk (254 miles)",
    "seller_type": "Private",
    "url": "https://www.autotrader.co.uk/car-details/202607274556226",
    "image": "media/202607274556226.jpg",
    "images_hires": [
     "media/hires/202607274556226_0.jpg",
     "media/hires/202607274556226_1.jpg",
     "media/hires/202607274556226_2.jpg",
     "media/hires/202607274556226_3.jpg"
    ],
    "paint": {
     "name": "Black",
     "hex": "#0d0d0f"
    },
    "keyword_hits": [
     "bucket seats"
    ],
    "keyword_flags": [
     "coilover"
    ],
    "score": 0,
    "first_seen": "2026-08-18",
    "days_listed": 48,
    "price_history": [
     {
      "date": "2026-08-18",
      "price": 27800
     },
     {
      "date": "2026-10-04",
      "price": 27100
     }
    ],
    "rank": 11
   },
   {
    "advert_id": "202609236303676",
    "title": "Audi RS4",
    "subtitle": "4.2 quattro 4dr",
    "attention_grabber": "+ 1 PREVIOUS OWNER + AUDI S/H",
    "price": 22240,
    "price_text": "£22,240",
    "year": 2006,
    "mileage": 92770,
    "mileage_text": "92,770 miles",
    "location": "Bristol (79 miles)",
    "seller_type": "Trade",
    "url": "https://www.autotrader.co.uk/car-details/202609236303676",
    "image": "media/202609236303676.jpg",
    "images_hires": [
     "media/hires/202609236303676_0.jpg",
     "media/hires/202609236303676_1.jpg",
     "media/hires/202609236303676_2.jpg",
     "media/hires/202609236303676_3.jpg"
    ],
    "paint": {
     "name": "Avus Silver",
     "hex": "#c9ccd1"
    },
    "keyword_hits": [],
    "keyword_flags": [],
    "score": 0,
    "first_seen": "2026-10-04",
    "days_listed": 1,
    "price_history": [
     {
      "date": "2026-10-04",
      "price": 22240
     }
    ],
    "rank": 12
   },
   {
    "advert_id": "202607254499482",
    "title": "Audi RS4",
    "subtitle": "4.2 quattro 4dr",
    "attention_grabber": null,
    "price": 10000,
    "price_text": "£10,000",
    "year": 2006,
    "mileage": 152000,
    "mileage_text": "152,000 miles",
    "location": "Middlesbrough (149 miles)",
    "seller_type": "Private",
    "url": "https://www.autotrader.co.uk/car-details/202607254499482",
    "image": "media/202607254499482.jpg",
    "images_hires": [
     "media/hires/202607254499482_0.jpg",
     "media/hires/202607254499482_1.jpg",
     "media/hires/202607254499482_2.jpg",
     "media/hires/202607254499482_3.jpg"
    ],
    "paint": {
     "name": "Black",
     "hex": "#0d0d0f"
    },
    "keyword_hits": [],
    "keyword_flags": [],
    "score": 0,
    "first_seen": "2026-08-18",
    "days_listed": 48,
    "price_history": [
     {
      "date": "2026-08-18",
      "price": 10000
     }
    ],
    "rank": 13
   },
   {
    "advert_id": "202408042534024",
    "title": "Audi RS4",
    "subtitle": "4.2 quattro 4dr",
    "attention_grabber": null,
    "price": 15949,
    "price_text": "£15,949",
    "year": 2006,
    "mileage": 95998,
    "mileage_text": "95,998 miles",
    "location": "Bradford (93 miles)",
    "seller_type": "Private",
    "url": "https://www.autotrader.co.uk/car-details/202408042534024",
    "image": "media/202408042534024.jpg",
    "images_hires": [
     "media/hires/202408042534024_0.jpg",
     "media/hires/202408042534024_1.jpg",
     "media/hires/202408042534024_2.jpg",
     "media/hires/202408042534024_3.jpg"
    ],
    "paint": {
     "name": "Sprint Blue",
     "hex": "#1757c2"
    },
    "keyword_hits": [
     "flat bottom"
    ],
    "keyword_flags": [
     "cat d",
     "cat n"
    ],
    "score": -1,
    "first_seen": "2026-07-12",
    "days_listed": 85,
    "price_history": [
     {
      "date": "2026-07-12",
      "price": 15949
     }
    ],
    "rank": 14
   },
   {
    "advert_id": "202608125020262",
    "title": "Audi RS4",
    "subtitle": "4.2 quattro 4dr",
    "attention_grabber": "Low owners & extensive FSH",
    "price": 14995,
    "price_text": "£14,995",
    "year": 2007,
    "mileage": 132000,
    "mileage_text": "132,000 miles",
    "location": "Southampton (114 miles)",
    "seller_type": "Private",
    "url": "https://www.autotrader.co.uk/car-details/202608125020262",
    "image": "media/202608125020262.jpg",
    "images_hires": [
     "media/hires/202608125020262_0.jpg",
     "media/hires/202608125020262_1.jpg",
     "media/hires/202608125020262_2.jpg",
     "media/hires/202608125020262_3.jpg"
    ],
    "paint": {
     "name": "Misano Red",
     "hex": "#b01526"
    },
    "keyword_hits": [],
    "keyword_flags": [
     "coilovers"
    ],
    "score": -1,
    "first_seen": "2026-08-18",
    "days_listed": 48,
    "price_history": [
     {
      "date": "2026-08-18",
      "price": 14995
     }
    ],
    "rank": 15
   }
  ],
  "gone": [
   {
    "advert_id": "202604171628465",
    "title": "Audi RS4",
    "subtitle": "4.2 quattro 4dr",
    "attention_grabber": "REVERSE CAMERA + CRUISE",
    "price": 21995,
    "price_text": "£21,995",
    "year": 2006,
    "mileage": 62070,
    "mileage_text": "62,070 miles",
    "location": "Bradford (90 miles)",
    "seller_type": "Trade",
    "url": "https://www.autotrader.co.uk/car-details/202604171628465",
    "image": "media/202604171628465.jpg",
    "images_hires": [
     "media/hires/202604171628465_0.jpg",
     "media/hires/202604171628465_1.jpg",
     "media/hires/202604171628465_2.jpg",
     "media/hires/202604171628465_3.jpg"
    ],
    "paint": {
     "name": "Black",
     "hex": "#0d0d0f"
    },
    "keyword_hits": [
     "flat bottom"
    ],
    "keyword_flags": [],
    "score": 1,
    "first_seen": "2026-07-12",
    "days_listed": 85,
    "price_history": [
     {
      "date": "2026-07-12",
      "price": 21995
     }
    ],
    "removed_date": "2026-10-04",
    "last_seen": "2026-08-19",
    "days_on_market": 84
   },
   {
    "advert_id": "202601129083619",
    "title": "Audi RS4",
    "subtitle": "4.2 quattro 4dr",
    "attention_grabber": "Full history, Wingback, Carbon",
    "price": 24999,
    "price_text": "£24,999",
    "year": 2007,
    "mileage": 93000,
    "mileage_text": "93,000 miles",
    "location": "Caldicot (71 miles)",
    "seller_type": "Private",
    "url": "https://www.autotrader.co.uk/car-details/202601129083619",
    "image": "media/202601129083619.jpg",
    "images_hires": [
     "media/hires/202601129083619_0.jpg",
     "media/hires/202601129083619_1.jpg",
     "media/hires/202601129083619_2.jpg",
     "media/hires/202601129083619_3.jpg"
    ],
    "paint": {
     "name": "Blue",
     "hex": "#1a4ba8"
    },
    "keyword_hits": [
     "wingback"
    ],
    "keyword_flags": [
     "remap"
    ],
    "score": 0,
    "first_seen": "2026-07-12",
    "days_listed": 85,
    "price_history": [
     {
      "date": "2026-07-12",
      "price": 24999
     }
    ],
    "removed_date": "2026-10-04",
    "last_seen": "2026-08-19",
    "days_on_market": 84
   },
   {
    "advert_id": "202607144158186",
    "title": "Audi RS4",
    "subtitle": "4.2 quattro 4dr",
    "attention_grabber": "RARE MANUAL! PIRELLI ZEROS!",
    "price": 19995,
    "price_text": "£19,995",
    "year": 2006,
    "mileage": 114769,
    "mileage_text": "114,769 miles",
    "location": "Wrexham (62 miles)",
    "seller_type": "Private",
    "url": "https://www.autotrader.co.uk/car-details/202607144158186",
    "image": "media/202607144158186.jpg",
    "images_hires": [
     "media/hires/202607144158186_0.jpg",
     "media/hires/202607144158186_1.jpg",
     "media/hires/202607144158186_2.jpg",
     "media/hires/202607144158186_3.jpg"
    ],
    "paint": {
     "name": "Silver",
     "hex": "#c9ccd1"
    },
    "keyword_hits": [],
    "keyword_flags": [
     "coilover"
    ],
    "score": -1,
    "first_seen": "2026-08-18",
    "days_listed": 48,
    "price_history": [
     {
      "date": "2026-08-18",
      "price": 19995
     }
    ],
    "removed_date": "2026-10-04",
    "last_seen": "2026-08-19",
    "days_on_market": 47
   },
   {
    "advert_id": "202607284595963",
    "title": "Audi RS4",
    "subtitle": "4.2 quattro 4dr",
    "attention_grabber": null,
    "price": 21500,
    "price_text": "£21,500",
    "year": 2007,
    "mileage": 86700,
    "mileage_text": "86,700 miles",
    "location": "Horsham (119 miles)",
    "seller_type": "Private",
    "url": "https://www.autotrader.co.uk/car-details/202607284595963",
    "image": "media/202607284595963.jpg",
    "images_hires": [
     "media/hires/202607284595963_0.jpg",
     "media/hires/202607284595963_1.jpg",
     "media/hires/202607284595963_2.jpg",
     "media/hires/202607284595963_3.jpg"
    ],
    "paint": {
     "name": "Sprint Blue",
     "hex": "#1757c2"
    },
    "keyword_hits": [
     "bucket seats",
     "flat-bottom",
     "recaro",
     "wingback"
    ],
    "keyword_flags": [],
    "score": 4,
    "first_seen": "2026-08-18",
    "days_listed": 48,
    "price_history": [
     {
      "date": "2026-08-18",
      "price": 21500
     }
    ],
    "removed_date": "2026-10-04",
    "last_seen": "2026-08-19",
    "days_on_market": 47
   },
   {
    "advert_id": "202606273670017",
    "title": "Audi RS4",
    "subtitle": "4.2 quattro 4dr",
    "attention_grabber": "2 OWNERS / FASH / BUCKETS",
    "price": 32989,
    "price_text": "£32,989",
    "year": 2007,
    "mileage": 35000,
    "mileage_text": "35,000 miles",
    "location": "Keighley (96 miles)",
    "seller_type": "Trade",
    "url": "https://www.autotrader.co.uk/car-details/202606273670017",
    "image": "media/202606273670017.jpg",
    "images_hires": [
     "media/hires/202606273670017_0.jpg",
     "media/hires/202606273670017_1.jpg",
     "media/hires/202606273670017_2.jpg",
     "media/hires/202606273670017_3.jpg"
    ],
    "paint": {
     "name": "Sprint Blue",
     "hex": "#1757c2"
    },
    "keyword_hits": [
     "bucket seats",
     "recaro"
    ],
    "keyword_flags": [],
    "score": 2,
    "first_seen": "2026-07-12",
    "days_listed": 85,
    "price_history": [
     {
      "date": "2026-07-12",
      "price": 32989
     }
    ],
    "removed_date": "2026-08-18",
    "last_seen": "2026-07-12",
    "days_on_market": 37
   },
   {
    "advert_id": "202606293709569",
    "title": "Audi RS4",
    "subtitle": "4.2 quattro 4dr",
    "attention_grabber": "SPRINT BLUE|WINGBACKS",
    "price": 27995,
    "price_text": "£27,995",
    "year": 2006,
    "mileage": 61500,
    "mileage_text": "61,500 miles",
    "location": "Ripon (116 miles)",
    "seller_type": "Trade",
    "url": "https://www.autotrader.co.uk/car-details/202606293709569",
    "image": "media/202606293709569.jpg",
    "images_hires": [
     "media/hires/202606293709569_0.jpg",
     "media/hires/202606293709569_1.jpg",
     "media/hires/202606293709569_2.jpg",
     "media/hires/202606293709569_3.jpg"
    ],
    "paint": {
     "name": "Sprint Blue",
     "hex": "#1757c2"
    },
    "keyword_hits": [
     "bucket seats",
     "recaro",
     "wingbacks"
    ],
    "keyword_flags": [],
    "score": 3,
    "first_seen": "2026-07-12",
    "days_listed": 85,
    "price_history": [
     {
      "date": "2026-07-12",
      "price": 27995
     }
    ],
    "removed_date": "2026-08-18",
    "last_seen": "2026-07-12",
    "days_on_market": 37
   },
   {
    "advert_id": "202602260223853",
    "title": "Audi RS4",
    "subtitle": "4.2 quattro 4dr",
    "attention_grabber": null,
    "price": 18995,
    "price_text": "£18,995",
    "year": 2007,
    "mileage": 115212,
    "mileage_text": "115,212 miles",
    "location": "Luton (76 miles)",
    "seller_type": "Trade",
    "url": "https://www.autotrader.co.uk/car-details/202602260223853",
    "image": "media/202602260223853.jpg",
    "images_hires": [
     "media/hires/202602260223853_0.jpg",
     "media/hires/202602260223853_1.jpg",
     "media/hires/202602260223853_2.jpg",
     "media/hires/202602260223853_3.jpg"
    ],
    "paint": {
     "name": "Black",
     "hex": "#0d0d0f"
    },
    "keyword_hits": [],
    "keyword_flags": [],
    "score": 0,
    "first_seen": "2026-07-12",
    "days_listed": 85,
    "price_history": [
     {
      "date": "2026-07-12",
      "price": 18995
     }
    ],
    "removed_date": "2026-08-18",
    "last_seen": "2026-07-12",
    "days_on_market": 37
   },
   {
    "advert_id": "202604221785655",
    "title": "Audi RS4",
    "subtitle": "4.2 quattro 4dr",
    "attention_grabber": "FOLDER OF RECEIPTS - WINGBACKS",
    "price": 19500,
    "price_text": "£19,500",
    "year": 2006,
    "mileage": 80700,
    "mileage_text": "80,700 miles",
    "location": "Loughborough (35 miles)",
    "seller_type": "Private",
    "url": "https://www.autotrader.co.uk/car-details/202604221785655",
    "image": "media/202604221785655.jpg",
    "images_hires": [
     "media/hires/202604221785655_0.jpg",
     "media/hires/202604221785655_1.jpg",
     "media/hires/202604221785655_2.jpg",
     "media/hires/202604221785655_3.jpg"
    ],
    "paint": {
     "name": "Grey",
     "hex": "#55595f"
    },
    "keyword_hits": [
     "wingbacks"
    ],
    "keyword_flags": [],
    "score": 1,
    "first_seen": "2026-07-12",
    "days_listed": 85,
    "price_history": [
     {
      "date": "2026-07-12",
      "price": 19500
     }
    ],
    "removed_date": "2026-08-18",
    "last_seen": "2026-07-12",
    "days_on_market": 37
   },
   {
    "advert_id": "202606253629245",
    "title": "Audi RS4",
    "subtitle": "4.2 quattro 4dr",
    "attention_grabber": "Milltek, Wingbacks, MRC Stg 2",
    "price": 19250,
    "price_text": "£19,250",
    "year": 2007,
    "mileage": 118200,
    "mileage_text": "118,200 miles",
    "location": "Manchester (72 miles)",
    "seller_type": "Private",
    "url": "https://www.autotrader.co.uk/car-details/202606253629245",
    "image": "media/202606253629245.jpg",
    "images_hires": [
     "media/hires/202606253629245_0.jpg",
     "media/hires/202606253629245_1.jpg",
     "media/hires/202606253629245_2.jpg",
     "media/hires/202606253629245_3.jpg"
    ],
    "paint": {
     "name": "Mugello Blue",
     "hex": "#1a3f8f"
    },
    "keyword_hits": [
     "bucket seats",
     "flat bottom",
     "wingbacks"
    ],
    "keyword_flags": [
     "coilovers"
    ],
    "score": 2,
    "first_seen": "2026-07-12",
    "days_listed": 85,
    "price_history": [
     {
      "date": "2026-07-12",
      "price": 19250
     }
    ],
    "removed_date": "2026-08-18",
    "last_seen": "2026-07-12",
    "days_on_market": 37
   },
   {
    "advert_id": "202606303748730",
    "title": "Audi RS4",
    "subtitle": "4.2 quattro 4dr",
    "attention_grabber": "Wingbacks,Carbon Clean + B14s",
    "price": 21995,
    "price_text": "£21,995",
    "year": 2006,
    "mileage": 107500,
    "mileage_text": "107,500 miles",
    "location": "Leatherhead (105 miles)",
    "seller_type": "Private",
    "url": "https://www.autotrader.co.uk/car-details/202606303748730",
    "image": "media/202606303748730.jpg",
    "images_hires": [
     "media/hires/202606303748730_0.jpg",
     "media/hires/202606303748730_1.jpg",
     "media/hires/202606303748730_2.jpg",
     "media/hires/202606303748730_3.jpg"
    ],
    "paint": {
     "name": "Black",
     "hex": "#0d0d0f"
    },
    "keyword_hits": [
     "bucket seats",
     "wingbacks"
    ],
    "keyword_flags": [
     "remap"
    ],
    "score": 1,
    "first_seen": "2026-07-12",
    "days_listed": 85,
    "price_history": [
     {
      "date": "2026-07-12",
      "price": 21995
     }
    ],
    "removed_date": "2026-08-18",
    "last_seen": "2026-07-12",
    "days_on_market": 37
   },
   {
    "advert_id": "202607124118952",
    "title": "Audi RS4",
    "subtitle": "4.2 quattro 4dr",
    "attention_grabber": "6K spent in last 20k miles!",
    "price": 12750,
    "price_text": "£12,750",
    "year": 2006,
    "mileage": 138000,
    "mileage_text": "138,000 miles",
    "location": "Norwich (130 miles)",
    "seller_type": "Private",
    "url": "https://www.autotrader.co.uk/car-details/202607124118952",
    "image": "media/202607124118952.jpg",
    "images_hires": [
     "media/hires/202607124118952_0.jpg",
     "media/hires/202607124118952_1.jpg",
     "media/hires/202607124118952_2.jpg",
     "media/hires/202607124118952_3.jpg"
    ],
    "paint": {
     "name": "Black",
     "hex": "#0d0d0f"
    },
    "keyword_hits": [
     "flat bottom"
    ],
    "keyword_flags": [],
    "score": 1,
    "first_seen": "2026-07-12",
    "days_listed": 85,
    "price_history": [
     {
      "date": "2026-07-12",
      "price": 12750
     }
    ],
    "removed_date": "2026-08-18",
    "last_seen": "2026-07-12",
    "days_on_market": 37
   }
  ]
 }
};
