// generated by site/build_data.py — do not edit
window.RS4_DATA = {
 "generated_at": "2026-07-12T22:31:38+01:00",
 "search_label": "Audi RS4 B7 · 2006–2008 · Manual · Petrol · UK-wide",
 "market": {
  "total_live": 14,
  "floor_price": 12750,
  "ceiling_price": 32989,
  "lowest_mileage": 35000,
  "days_tracked": 1,
  "trend": [
   {
    "date": "2026-07-12",
    "live": 14,
    "new": 1,
    "price_changed": 0,
    "removed": 0,
    "floor": 12750,
    "median": 21995,
    "ceiling": 32989
   }
  ],
  "listings": [
   {
    "advert_id": "202606293709569",
    "title": "Audi RS4",
    "subtitle": "4.2 quattro 4dr",
    "attention_grabber": "SPRINT BLUE|WINGBACKS",
    "price": 27995,
    "price_text": "£27,995",
    "year": 2006,
    "mileage": 61500,
    "mileage_text": "61,500 miles",
    "location": "Ripon (116 miles)",
    "seller_type": "Trade",
    "url": "https://www.autotrader.co.uk/car-details/202606293709569",
    "image": "media/202606293709569.jpg",
    "images_hires": [
     "media/hires/202606293709569_0.jpg",
     "media/hires/202606293709569_1.jpg",
     "media/hires/202606293709569_2.jpg",
     "media/hires/202606293709569_3.jpg"
    ],
    "paint": {
     "name": "Sprint Blue",
     "hex": "#1757c2"
    },
    "keyword_hits": [
     "bucket seats",
     "recaro",
     "wingbacks"
    ],
    "keyword_flags": [],
    "score": 3,
    "first_seen": "2026-07-12",
    "days_listed": 0,
    "price_history": [
     {
      "date": "2026-07-12",
      "price": 27995
     }
    ],
    "rank": 1
   },
   {
    "advert_id": "202606273670017",
    "title": "Audi RS4",
    "subtitle": "4.2 quattro 4dr",
    "attention_grabber": "2 OWNERS / FASH / BUCKETS",
    "price": 32989,
    "price_text": "£32,989",
    "year": 2007,
    "mileage": 35000,
    "mileage_text": "35,000 miles",
    "location": "Keighley (96 miles)",
    "seller_type": "Trade",
    "url": "https://www.autotrader.co.uk/car-details/202606273670017",
    "image": "media/202606273670017.jpg",
    "images_hires": [
     "media/hires/202606273670017_0.jpg",
     "media/hires/202606273670017_1.jpg",
     "media/hires/202606273670017_2.jpg",
     "media/hires/202606273670017_3.jpg"
    ],
    "paint": {
     "name": "Sprint Blue",
     "hex": "#1757c2"
    },
    "keyword_hits": [
     "bucket seats",
     "recaro"
    ],
    "keyword_flags": [],
    "score": 2,
    "first_seen": "2026-07-12",
    "days_listed": 0,
    "price_history": [
     {
      "date": "2026-07-12",
      "price": 32989
     }
    ],
    "rank": 2
   },
   {
    "advert_id": "202606183421720",
    "title": "Audi RS4",
    "subtitle": "4.2 quattro 4dr",
    "attention_grabber": "WARRANTY | DELIVERY",
    "price": 22990,
    "price_text": "£22,990",
    "year": 2007,
    "mileage": 101402,
    "mileage_text": "101,402 miles",
    "location": "Congleton (50 miles)",
    "seller_type": "Trade",
    "url": "https://www.autotrader.co.uk/car-details/202606183421720",
    "image": "media/202606183421720.jpg",
    "images_hires": [
     "media/hires/202606183421720_0.jpg",
     "media/hires/202606183421720_1.jpg",
     "media/hires/202606183421720_2.jpg",
     "media/hires/202606183421720_3.jpg"
    ],
    "paint": {
     "name": "Black",
     "hex": "#0d0d0f"
    },
    "keyword_hits": [
     "recaro",
     "sports seat"
    ],
    "keyword_flags": [],
    "score": 2,
    "first_seen": "2026-07-12",
    "days_listed": 0,
    "price_history": [
     {
      "date": "2026-07-12",
      "price": 22990
     }
    ],
    "rank": 3
   },
   {
    "advert_id": "202606253629245",
    "title": "Audi RS4",
    "subtitle": "4.2 quattro 4dr",
    "attention_grabber": "Milltek, Wingbacks, MRC Stg 2",
    "price": 19250,
    "price_text": "£19,250",
    "year": 2007,
    "mileage": 118200,
    "mileage_text": "118,200 miles",
    "location": "Manchester (72 miles)",
    "seller_type": "Private",
    "url": "https://www.autotrader.co.uk/car-details/202606253629245",
    "image": "media/202606253629245.jpg",
    "images_hires": [
     "media/hires/202606253629245_0.jpg",
     "media/hires/202606253629245_1.jpg",
     "media/hires/202606253629245_2.jpg",
     "media/hires/202606253629245_3.jpg"
    ],
    "paint": {
     "name": "Mugello Blue",
     "hex": "#1a3f8f"
    },
    "keyword_hits": [
     "bucket seats",
     "flat bottom",
     "wingbacks"
    ],
    "keyword_flags": [
     "coilovers"
    ],
    "score": 2,
    "first_seen": "2026-07-12",
    "days_listed": 0,
    "price_history": [
     {
      "date": "2026-07-12",
      "price": 19250
     }
    ],
    "rank": 4
   },
   {
    "advert_id": "202604171628465",
    "title": "Audi RS4",
    "subtitle": "4.2 quattro 4dr",
    "attention_grabber": "REVERSE CAMERA + CRUISE",
    "price": 21995,
    "price_text": "£21,995",
    "year": 2006,
    "mileage": 62070,
    "mileage_text": "62,070 miles",
    "location": "Bradford (90 miles)",
    "seller_type": "Trade",
    "url": "https://www.autotrader.co.uk/car-details/202604171628465",
    "image": "media/202604171628465.jpg",
    "images_hires": [
     "media/hires/202604171628465_0.jpg",
     "media/hires/202604171628465_1.jpg",
     "media/hires/202604171628465_2.jpg",
     "media/hires/202604171628465_3.jpg"
    ],
    "paint": {
     "name": "Black",
     "hex": "#0d0d0f"
    },
    "keyword_hits": [
     "flat bottom"
    ],
    "keyword_flags": [],
    "score": 1,
    "first_seen": "2026-07-12",
    "days_listed": 0,
    "price_history": [
     {
      "date": "2026-07-12",
      "price": 21995
     }
    ],
    "rank": 5
   },
   {
    "advert_id": "202604221785655",
    "title": "Audi RS4",
    "subtitle": "4.2 quattro 4dr",
    "attention_grabber": "FOLDER OF RECEIPTS - WINGBACKS",
    "price": 19500,
    "price_text": "£19,500",
    "year": 2006,
    "mileage": 80700,
    "mileage_text": "80,700 miles",
    "location": "Loughborough (35 miles)",
    "seller_type": "Private",
    "url": "https://www.autotrader.co.uk/car-details/202604221785655",
    "image": "media/202604221785655.jpg",
    "images_hires": [
     "media/hires/202604221785655_0.jpg",
     "media/hires/202604221785655_1.jpg",
     "media/hires/202604221785655_2.jpg",
     "media/hires/202604221785655_3.jpg"
    ],
    "paint": {
     "name": "Grey",
     "hex": "#55595f"
    },
    "keyword_hits": [
     "wingbacks"
    ],
    "keyword_flags": [],
    "score": 1,
    "first_seen": "2026-07-12",
    "days_listed": 0,
    "price_history": [
     {
      "date": "2026-07-12",
      "price": 19500
     }
    ],
    "rank": 6
   },
   {
    "advert_id": "202607073963384",
    "title": "Audi RS4",
    "subtitle": "4.2 quattro 4dr",
    "attention_grabber": "FSH+BUCKETS+MILLTEK+BOSE",
    "price": 18995,
    "price_text": "£18,995",
    "year": 2007,
    "mileage": 106200,
    "mileage_text": "106,200 miles",
    "location": "Birmingham (5 miles)",
    "seller_type": "Trade",
    "url": "https://www.autotrader.co.uk/car-details/202607073963384",
    "image": "media/202607073963384.jpg",
    "images_hires": [
     "media/hires/202607073963384_0.jpg",
     "media/hires/202607073963384_1.jpg",
     "media/hires/202607073963384_2.jpg",
     "media/hires/202607073963384_3.jpg"
    ],
    "paint": {
     "name": "Daytona Grey",
     "hex": "#3b3f45"
    },
    "keyword_hits": [
     "bucket seats"
    ],
    "keyword_flags": [],
    "score": 1,
    "first_seen": "2026-07-12",
    "days_listed": 0,
    "price_history": [
     {
      "date": "2026-07-12",
      "price": 18995
     }
    ],
    "rank": 7
   },
   {
    "advert_id": "202606303748730",
    "title": "Audi RS4",
    "subtitle": "4.2 quattro 4dr",
    "attention_grabber": "Wingbacks,Carbon Clean + B14s",
    "price": 21995,
    "price_text": "£21,995",
    "year": 2006,
    "mileage": 107500,
    "mileage_text": "107,500 miles",
    "location": "Leatherhead (105 miles)",
    "seller_type": "Private",
    "url": "https://www.autotrader.co.uk/car-details/202606303748730",
    "image": "media/202606303748730.jpg",
    "images_hires": [
     "media/hires/202606303748730_0.jpg",
     "media/hires/202606303748730_1.jpg",
     "media/hires/202606303748730_2.jpg",
     "media/hires/202606303748730_3.jpg"
    ],
    "paint": {
     "name": "Black",
     "hex": "#0d0d0f"
    },
    "keyword_hits": [
     "bucket seats",
     "wingbacks"
    ],
    "keyword_flags": [
     "remap"
    ],
    "score": 1,
    "first_seen": "2026-07-12",
    "days_listed": 0,
    "price_history": [
     {
      "date": "2026-07-12",
      "price": 21995
     }
    ],
    "rank": 8
   },
   {
    "advert_id": "202607124118952",
    "title": "Audi RS4",
    "subtitle": "4.2 quattro 4dr",
    "attention_grabber": "6K spent in last 20k miles!",
    "price": 12750,
    "price_text": "£12,750",
    "year": 2006,
    "mileage": 138000,
    "mileage_text": "138,000 miles",
    "location": "Norwich (130 miles)",
    "seller_type": "Private",
    "url": "https://www.autotrader.co.uk/car-details/202607124118952",
    "image": "media/202607124118952.jpg",
    "images_hires": [
     "media/hires/202607124118952_0.jpg",
     "media/hires/202607124118952_1.jpg",
     "media/hires/202607124118952_2.jpg",
     "media/hires/202607124118952_3.jpg"
    ],
    "paint": {
     "name": "Black",
     "hex": "#0d0d0f"
    },
    "keyword_hits": [
     "flat bottom"
    ],
    "keyword_flags": [],
    "score": 1,
    "first_seen": "2026-07-12",
    "days_listed": 0,
    "price_history": [
     {
      "date": "2026-07-12",
      "price": 12750
     }
    ],
    "rank": 9
   },
   {
    "advert_id": "202605252687946",
    "title": "Audi RS4",
    "subtitle": "4.2 quattro 4dr",
    "attention_grabber": "stunning example!! B7 Audi RS!",
    "price": 23800,
    "price_text": "£23,800",
    "year": 2007,
    "mileage": 66000,
    "mileage_text": "66,000 miles",
    "location": "Biggleswade (75 miles)",
    "seller_type": "Private",
    "url": "https://www.autotrader.co.uk/car-details/202605252687946",
    "image": "media/202605252687946.jpg",
    "images_hires": [
     "media/hires/202605252687946_0.jpg",
     "media/hires/202605252687946_1.jpg",
     "media/hires/202605252687946_2.jpg",
     "media/hires/202605252687946_3.jpg"
    ],
    "paint": {
     "name": "Mugello Blue",
     "hex": "#1a3f8f"
    },
    "keyword_hits": [],
    "keyword_flags": [],
    "score": 0,
    "first_seen": "2026-07-12",
    "days_listed": 0,
    "price_history": [
     {
      "date": "2026-07-12",
      "price": 23800
     }
    ],
    "rank": 10
   },
   {
    "advert_id": "202511047646815",
    "title": "Audi RS4",
    "subtitle": "4.2 quattro 4dr",
    "attention_grabber": "3 MONTHS WARRANTY INCLUDED!",
    "price": 21999,
    "price_text": "£21,999",
    "year": 2007,
    "mileage": 82000,
    "mileage_text": "82,000 miles",
    "location": "Rossendale (88 miles)",
    "seller_type": "Trade",
    "url": "https://www.autotrader.co.uk/car-details/202511047646815",
    "image": "media/202511047646815.jpg",
    "images_hires": [
     "media/hires/202511047646815_0.jpg",
     "media/hires/202511047646815_1.jpg",
     "media/hires/202511047646815_2.jpg",
     "media/hires/202511047646815_3.jpg"
    ],
    "paint": {
     "name": "Black",
     "hex": "#0d0d0f"
    },
    "keyword_hits": [],
    "keyword_flags": [],
    "score": 0,
    "first_seen": "2026-07-12",
    "days_listed": 0,
    "price_history": [
     {
      "date": "2026-07-12",
      "price": 21999
     }
    ],
    "rank": 11
   },
   {
    "advert_id": "202601129083619",
    "title": "Audi RS4",
    "subtitle": "4.2 quattro 4dr",
    "attention_grabber": "Full history, Wingback, Carbon",
    "price": 24999,
    "price_text": "£24,999",
    "year": 2007,
    "mileage": 93000,
    "mileage_text": "93,000 miles",
    "location": "Caldicot (71 miles)",
    "seller_type": "Private",
    "url": "https://www.autotrader.co.uk/car-details/202601129083619",
    "image": "media/202601129083619.jpg",
    "images_hires": [
     "media/hires/202601129083619_0.jpg",
     "media/hires/202601129083619_1.jpg",
     "media/hires/202601129083619_2.jpg",
     "media/hires/202601129083619_3.jpg"
    ],
    "paint": {
     "name": "Blue",
     "hex": "#1a4ba8"
    },
    "keyword_hits": [
     "wingback"
    ],
    "keyword_flags": [
     "remap"
    ],
    "score": 0,
    "first_seen": "2026-07-12",
    "days_listed": 0,
    "price_history": [
     {
      "date": "2026-07-12",
      "price": 24999
     }
    ],
    "rank": 12
   },
   {
    "advert_id": "202602260223853",
    "title": "Audi RS4",
    "subtitle": "4.2 quattro 4dr",
    "attention_grabber": null,
    "price": 18995,
    "price_text": "£18,995",
    "year": 2007,
    "mileage": 115212,
    "mileage_text": "115,212 miles",
    "location": "Luton (76 miles)",
    "seller_type": "Trade",
    "url": "https://www.autotrader.co.uk/car-details/202602260223853",
    "image": "media/202602260223853.jpg",
    "images_hires": [
     "media/hires/202602260223853_0.jpg",
     "media/hires/202602260223853_1.jpg",
     "media/hires/202602260223853_2.jpg",
     "media/hires/202602260223853_3.jpg"
    ],
    "paint": {
     "name": "Black",
     "hex": "#0d0d0f"
    },
    "keyword_hits": [],
    "keyword_flags": [],
    "score": 0,
    "first_seen": "2026-07-12",
    "days_listed": 0,
    "price_history": [
     {
      "date": "2026-07-12",
      "price": 18995
     }
    ],
    "rank": 13
   },
   {
    "advert_id": "202408042534024",
    "title": "Audi RS4",
    "subtitle": "4.2 quattro 4dr",
    "attention_grabber": null,
    "price": 15949,
    "price_text": "£15,949",
    "year": 2006,
    "mileage": 95998,
    "mileage_text": "95,998 miles",
    "location": "Bradford (93 miles)",
    "seller_type": "Private",
    "url": "https://www.autotrader.co.uk/car-details/202408042534024",
    "image": "media/202408042534024.jpg",
    "images_hires": [
     "media/hires/202408042534024_0.jpg",
     "media/hires/202408042534024_1.jpg",
     "media/hires/202408042534024_2.jpg",
     "media/hires/202408042534024_3.jpg"
    ],
    "paint": {
     "name": "Sprint Blue",
     "hex": "#1757c2"
    },
    "keyword_hits": [
     "flat bottom"
    ],
    "keyword_flags": [
     "cat d",
     "cat n"
    ],
    "score": -1,
    "first_seen": "2026-07-12",
    "days_listed": 0,
    "price_history": [
     {
      "date": "2026-07-12",
      "price": 15949
     }
    ],
    "rank": 14
   }
  ],
  "gone": []
 }
};
